// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6r4Ndy8tMDJRyi68YNgmVRq8mCKWxbM',
    appId: '1:79200691774:web:560283b297d4d7148d536f',
    messagingSenderId: '79200691774',
    projectId: 'rasoi-3c2cc',
    authDomain: 'rasoi-3c2cc.firebaseapp.com',
    storageBucket: 'rasoi-3c2cc.appspot.com',
    measurementId: 'G-P7RTTT7Q39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZoDQ0ocLfML84jWNJOFVe_yZOsIYulw',
    appId: '1:79200691774:android:a40de408d6fa82eb8d536f',
    messagingSenderId: '79200691774',
    projectId: 'rasoi-3c2cc',
    storageBucket: 'rasoi-3c2cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX4Aqpbk-eUbzgfKRwhmg44ADIeyVzeCI',
    appId: '1:79200691774:ios:efcc949f67420c978d536f',
    messagingSenderId: '79200691774',
    projectId: 'rasoi-3c2cc',
    storageBucket: 'rasoi-3c2cc.appspot.com',
    iosBundleId: 'com.example.rasoiriders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX4Aqpbk-eUbzgfKRwhmg44ADIeyVzeCI',
    appId: '1:79200691774:ios:2e3080b7a20075078d536f',
    messagingSenderId: '79200691774',
    projectId: 'rasoi-3c2cc',
    storageBucket: 'rasoi-3c2cc.appspot.com',
    iosBundleId: 'com.example.rasoiriders.RunnerTests',
  );
}
